engines:
  haxe-checkstyle:
    enabled: true
  markdownlint:
    enabled: true
    exclude_fingerprints:
    - 6d2c708cc8dd7b28fdfc03e5f9bc7d6d
    checks:
      MD013:
        enabled: false
ratings:
  paths:
    - "**.hx"
    - "**.md"
