language: haxe

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - "development"

sudo: false

addons:
  apt:
    packages:
    - mono-mcs

install:
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      brew update;
      brew install mono;
    fi
  - haxelib install hxcs
  - haxelib install hscript
  - git clone https://github.com/haxeui/haxeui-core.git --depth=1
  - haxelib dev haxeui-core haxeui-core

script:
  - cd $TRAVIS_BUILD_DIR
  - haxe test.hxml
