version: "{build}"

clone_folder: C:\projects\haxeui-xwt

clone_depth: 1

environment:
    global:
        ROOT: C:\projects\haxeui-xwt
        HAXELIB_ROOT: C:\projects\haxelib

install:
    # Install haxe
    - cinst haxe -y
    - RefreshEnv
    - haxe -version
    - neko -version
    # Setup haxe
    - mkdir "%HAXELIB_ROOT%"
    - haxelib setup "%HAXELIB_ROOT%"
    # Dependencies
    - haxelib install hxcs
    - haxelib install hscript
    - haxelib git haxeui-core https://github.com/haxeui/haxeui-core

build_script:
    - haxelib dev haxeui-xwt %ROOT%

test_script:
    - cd %APPVEYOR_BUILD_FOLDER%
    - haxe test.hxml
